DefaultContentLanguage = "de"
baseURL = "https://rollenspieltage.ch/"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "gilde-der-nacht"
themesDir = "../../themes"

[languages]
[languages.de]
languageName = "Deutsch"
title = "Luzerner Rollenspieltage"
weight = 1
[languages.de.params]
footer = "Die Luzerner Rollenspieltage werden organisiert durch den Spielverein, [Gilde der Nacht](https://gildedernacht.ch)."
[languages.en]
languageName = "English"
title = "Luzerner Rollenspieltage"
weight = 2
[languages.en.params]
footer = "The Luzerner Rollenspieltage are organised by the game society, [Gilde der Nacht](https://gildedernacht.ch)."

[params]
discord = "https://discord.gg/G7mkTTB"
facebook = "https://www.facebook.com/events/417456298837224/"
meetup = "https://www.meetup.com/de-DE/Spieltreffen-Luzern/events/261972612/"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
